//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farfaded.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<tblFlt> tblFlts { get; set; }
        public virtual DbSet<tblBlckOfFlt> tblBlckOfFlts { get; set; }
        public virtual DbSet<tlbService> tlbServices { get; set; }
        public virtual DbSet<tblSrvcInFlt> tblSrvcInFlts { get; set; }
        public virtual DbSet<tblSrvcInFltHstr> tblSrvcInFltHstrs { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tlbTarif> tlbTarifs { get; set; }
        public virtual DbSet<tblTarifHstr> tblTarifHstrs { get; set; }
        public virtual DbSet<tblControlType> tblControlTypes { get; set; }
        public virtual DbSet<tblControl> tblControls { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<C__MigrationHistory1> C__MigrationHistory1 { get; set; }
    }
}
