//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farfaded.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblControl
    {
        public int IdControl { get; set; }
        public string ControlName { get; set; }
        public int IdControlType { get; set; }
        public int IdFlt { get; set; }
        public int ControlValue { get; set; }
        public bool ControlValueLog { get; set; }
    
        public virtual tblControlType tblControlType { get; set; }
        public virtual tblFlt tblFlt { get; set; }
    }
}
